### PR TITLE
[Fix] antifarming weakness

### PR DESCRIPTION
**Pull request by LazyGon**
Fix bug that dispenser can use fish bucket.

### CODE REVIEW

**Comment by LazyGon** [comment]
I did not realize this bug before creating PR for kelp and sea grass bug...

**Comment by LazyGon** [comment]
I will commit patch about generating water source by kelp growth, please wait.

**Comment by RoboMWM** [comment]
No problem, whenever it's ready just click the "Ready for review" button.

**Comment by LazyGon** [comment]
In vanilla minecraft, sea grass or kelp fertilized with bone meal can replace flowing water into water source. In this case flowing water must be **falling** water (level is 8-15).
Now, non-bypassed user cannot generate water source in this way.

Kelp can grow without bone meal. This also can change water.
Cancelled these kelp growth which can change water.

**Comment by LazyGon** [comment]
We may need another scoreboard message for this limitation.

**Comment by RoboMWM** [comment]
Yea, I'm wondering if this should be another config option now that I think of it. The idea behind water buckets not creating water sources is so it isn't easy to just generate new sources from a mere bucket. EHM does _not_ block using harvesting ice to create sources though - as this is more difficult.

Is kelp/seagrass easy to obtain and use to create water sources?

**Comment by LazyGon** [comment]
I think it not difficult.
See [this reproduction video](https://youtu.be/s6P0tZ3G-F0).
And [this video](https://youtu.be/8IIaVBGTGYg) is how patched EHM denied creating water source.
(To see chat, you need to select 1080p (HD))

**Comment by RoboMWM** [comment]
Thank you for the detailed video! Yea, I figured that's how one could work around creating a water source with a bucket, they just need some extra materials and timing.

It probably does make sense to trigger a tutorial message or make a new one. It can stay as part of the same config option, or if you'd like, you can create another option - as thinking about this more, it makes sense for it to remain part of the same feature.

**Comment by LazyGon** [comment]
OK.
If you do not like added notification message or config message path, tell me new string you like.

**Comment by LazyGon** [comment]
I now recognized what you told me to implements differed what I thought.
It was my misunderstanding :p

And, I should divide this PR again into two, one is to deny dispenser fish bucket and another is kelp water creation patch.

(Sorry for my inactiveness. I was busy to deal with other things...)

**Comment by LazyGon** [comment]
So, close this PR once.

**Comment by RoboMWM** [comment]
Oh, I thought I pulled an earlier PR that superceded this. mk.

**Comment by LazyGon** [comment]
The earlier PR maybe [this](https://github.com/MLG-Fortress/ExtraHardMode/commit/690ab0195ea5d918b6a03885da19192bf729b0d4), which fixes putting seagrasses in marked water leaves water.

In my opinion, marked water should not be changed because marked blocks are unbreakable. The leaving mark alone is another bug that must be fixed.
Seagrasses will do it so I blocked the weakness.

Then, in minecraft default specification flowing water can become water source by kelp is a little different way.

Reproduction way, result, and using item is same but another bug, that is confusing. I should have explained more at PR above sorry.

**Comment by LazyGon** [comment]
Or we can change code to remove marks at where kelp is put.

**Comment by RoboMWM** [comment]
What do you mean by"marked" water?

Perhaps I need to review the new water stuff added in 1.13, sounds like it's complex.

**Comment by LazyGon** [comment]
Wait, I explained something wrong...

When player put water from bucket, the block is marked. I call the block "marked water".
I checked src and find that players cannot take water which is marked. Unbreakable is not correct. I may have been tired then...?

If player put kelp in marked water and then break it, marked water is left alone. The water cannot be removed by bucket.
I thought that is not regular behaver.

**Pull request closed without merging**
