### PR TITLE
Config option to set dragon health

### PR DESCRIPTION
**Pull request by erik1988**
Allows to set the dragons health on spawn.

### CODE REVIEW

**Comment by erik1988** [comment]
This might have a bug. just hold on for a few seconds so I can test it. :)

**Comment by erik1988** [comment]
Ok we are good to go on this one. Everything works well :)

**Comment by RoboMWM** [comment]
Only concern I have is setting to 800 by default. Sure, it's "harder," in that it just takes longer to finish. I'd be more interested in more damage/other things to worry about unless it's super easy to burst down at that level. Maybe more attacks or AoE when it's just a sitting duck on the ground?

I'd also be interested in more health per person (and to keep it proportional, increase both maxhealth and regular health(?))

**Comment by erik1988** [comment]
Two people was able to take down the dragon on my server, sure they had some problems but they manage. I was also able to almost kill him myself when I was trying it on my own, until that dragon tipped me over the edge, it had like 5% life left when I died. 

Most importantly it did not feel like a grid, the reason is that mojang made the dragon fly down to the middle and its super vulnerable and dies very fast. If you have allot of people in good gear its not going to be that hard even with 800.  But if you really want it lowered I dont have a problem with that, since I can just make it 800 on my build anyways. 

Im not sure what you mean about regular health vs max health tho.

**Comment by RoboMWM** [comment]
> Im not sure what you mean about regular health vs max health tho.

That's just if multiple players join in the fight (vs. original amount) - so difficulty increases as more players join (but doesn't revert "progress" so to speak). My example was just a way to implement said "difficulty increase," at least in terms of dragon health - increasing its maxhealth but also its health a bit (so if it's at 50% it remains at 50% health).

> the reason is that mojang made the dragon fly down to the middle and its super vulnerable and dies very fast.

Yes I noticed this too. Adding more health works to last for this yea but I was just suggesting perhaps it could do some other attacks other than just sitting there with a small AoE (or w/e it does when it's flapping its wings there).

**Pull request merged**
