### PR TITLE
[Remove] comment out invalid test

### PR DESCRIPTION
**Pull request by LazyGon**
PR divided #222

With PR #224 , we can become able to build this source successfully.

### CODE REVIEW

**Comment by RoboMWM** [comment]
What's wrong with this test?

**Comment by LazyGon** [comment]
Test class which has no @Test method is invalid and test will fail.
See #224 [AppVeyor check](https://ci.appveyor.com/project/RoboMWM39862/extrahardmode/builds/33297464#L693)

**Comment by LazyGon** [comment]
Or, other valid test is needed.

**Comment by LazyGon** [comment]
Tests are closely related with design policy.
So if you think other tests are needed, I recommend to add them yourself.

**Comment by RoboMWM** [comment]
Well you're updating the test suite version - you're bumping it a major version, which will almost always result in breakages. Is the breakage here too much to easily update? Or is it something else?

**Comment by LazyGon** [comment]
As result of some research, I have found that there is only one breakage.
The breakage appears #224 AppVeyor check.
After JUnit4.11, class with `@RunWith` and without `@Test` method will produce exception in test.
Other test classes work as they are.

And, what we have to do is to write test that is fit with current main code.
This may be a little tough.

**Pull request closed without merging**
