### PR TITLE
[Change] use static method in static way

### PR DESCRIPTION
**Pull request by LazyGon**
PR divided #222

### CODE REVIEW

**Comment by RoboMWM** [comment]
why? I know the IDE says it's static but I prefer using the instance if it's there. In fact, is there any reason why it's static in the first place?

**Comment by LazyGon** [comment]
If there's no reason, IDE will not say to do so.
This style can cause [rare mistake](https://www.intertech.com/Blog/a-static-method-should-be-accessed-in-a-static-way/).
I believe this change is based on de facto standard.

This PR is not very important. So if you do not agree, you do not have to merge.

**Comment by LazyGon** [comment]
This PR will never be merged. I close this.

**Comment by RoboMWM** [comment]
I just haven't gotten around to seeing if those should really be static or not. Since this was originally BigScary's plugin (a long time ago) it's likely that these may have been his leftovers.

**Comment by RoboMWM** [comment]
Since I've decided to deprioritize these projects, I'm not gonna spend time checking for "static abuse" stuff, so I guess this PR is fine.

**Pull request merged**
