### PR TITLE
Update for 1.18, which removed Biome.SWAMP_HILLS

### LINKED ISSUE #290: Support 1.18
1.18 will be released 11/30.  Could you ready support for 1.18 to ease the transition?  Maybe release a build in advance?  Thank you.

### PR DESCRIPTION
**Pull request by alexchandel**
Fixes #290

### CODE REVIEW

**Comment by alexchandel** [comment]
The AppVeyor config appears to be broken.

**Comment by OhNo2** [comment]
So is this usable? Can you successfully build it into a jar?

**Comment by RoboMWM** [comment]
Would be nice if we can get appveyor fixed first. Think tests failed or something when moving to jdk16 so yea.

**Comment by RoboMWM** [comment]
see https://github.com/TechFortress/GriefPrevention/pull/1663 for a reference. I can make the change but I'm currently prioritizing GP, so if anyone wants to make the change and test for any other issues please do so, thanks.

**Comment by GiorgioBrux** [comment]
Can we merge this? It should be the only blocking issue for a build.

**Comment by RoboMWM** [comment]
thought I did but I guess I didn't

**Pull request merged**
