### PR TITLE
Quick fix for Scoreboard Notifier

### PR DESCRIPTION
**Pull request by Vanmc**
#40 
Just removed ChatColor.RED + "ExtraHardmode" on the SB_MSG_TITLE and replaced it with a color code "&4ExtraHardMode" 

Also went back to spigot repo again was having hard time trying to compile with paper spigot repo..

### CODE REVIEW

**Comment by RoboMWM** [comment]
Hmm, what issues were you having with the paper repo?

**Comment by RoboMWM** [comment]
Not sure how an ampersand will automatically be converted to the color code. A section symbol, yes, but not an ampersand alone. Either way, ChatColor should be providing the proper formatting, so that's odd. Perhaps if you could ask around in the #spigot IRC channel

**Comment by Vanmc** [comment]
`Could not transfer metadata com.destroystokyo.paper:paper-api:1.9.2-R0.1-SNAPSHOT/maven-metadata.xml from/to destroystokyo-repo (https://repo.destroystokyo.com/content/groups/public/): peer not authenticatedFailure to transfer com.destroystokyo.paper:paper-api:1.9.2-R0.1-SNAPSHOT/maven-metadata.xml from https://repo.destroystokyo.com/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of destroystokyo-repo has elapsed or updates are forced. Original error: Could not transfer metadata com.destroystokyo.paper:paper-api:1.9.2-R0.1-SNAPSHOT/maven-metadata.xml from/to destroystokyo-repo (https://repo.destroystokyo.com/content/groups/public/): peer not authenticated`

**Comment by Vanmc** [comment]
I keep getting peer not authenticated for the paper spigot repo here is the link http://pastebin.com/qwPX4y8R as for the ampersand let me look into it further.

**Comment by Vanmc** [comment]
Alright I think i found the culprit and why &4 works or without using ChatColor.Red and why it produces wierd symbol

MessageConfig.java
`    @Override
    public String getString(ConfigNode node)
    {
        return ChatColor.translateAlternateColorCodes('&', super.getString(node));
    }
` 

MsgModule
`    public void sendPopup(Player player, MsgCategory category, String message)
    {
        if (popupsAreEnabled(category))
        {
            int length;
            ChatColor titleColor;
            ChatColor textColor;
            String titleText = messages.getString(MessageNode.SB_MSG_TITLE);`

so what happen is there is a redundancy on implementing the colors that is why we keep getting those weird symbols

I also noticed ChatColor textColor; which is not used at all on the other hand I think the reason why 
`            if (messages.getBoolean(MessageNode.SB_MSG_REMOVE_COLOR))
                message = ChatColor.stripColor(message);`
does not remove the colors even its FALSE its because the & codes were not parse

**Comment by Vanmc** [comment]
The messages config is kind of a mess with all those &color codes in messages. What I could suggest is just remove those and have and just use the Textcolor that is assigned on each category to do the work. Anyway the users can still edit it themselves if they want to customize.

As for the paper spigot despite updating the jdk to 8 still won't work. I am starting to think its ssl certificate which probably obvious by now by the error XD

**Comment by RoboMWM** [comment]
Paper should've fixed their SSL errors, at least on Windows it works now (LetsEncrypt certificate). What OS are you using? Also, it seems you're still trying to pull the spigot API from that log.

> The messages config is kind of a mess with all those &color codes in messages. What I could suggest is just remove those and have and just use the Textcolor that is assigned on each category to do the work. Anyway the users can still edit it themselves if they want to customize.

Sounds like a good plan to me.

**Comment by Vanmc** [comment]
I'm using Windows 7 and yes I am still trying to pull from spigot API we'll push quick change back to paper spigot quick. I'll solve my repo compiling issues later on been up all night need some sleep.

**Comment by Vanmc** [comment]
There done :D

**Comment by RoboMWM** [comment]
Lol I'll fix it, seems to be pulling the spigot api instead of paper

**Comment by RoboMWM** [comment]
Other than pulling my change for fixing the paper repo, could you check to see if you can still change colors in messages.yml still? Other than double checking that, should be good to go, thanks!

**Comment by Vanmc** [comment]
If you want to customize the color of scoreboard title just use color codes. e.g.  '&4ExtraHardMode'
If you want to customize the color of each message aside the from the title or highlight make sure Remove All Color Codes: false and be aware that color codes only apply to each line. e.g. Msg: "&4Sorry, you can't place ore next to stone." and the in game output is something along this 

`ExtraHardMode`
`Sorry, you can            - 1`
`'t place ore next to sto- 2`
`ne                                -3`

What will happen only Sorry, you can will be colored dark red which is &4 and the rest will default to the assign category color which is Textcolor.  I think this is a limitation of scoreboard and its API it is using. So what you have do to is Msg: "&4Sorry, you can'&4t place ore next to sto&4ne." or if there is no ' <-- single quote then just do this -->  Msg: '&4Sorry, you can&4t place ore next to sto&4ne.'

**Comment by RoboMWM** [comment]
> What will happen only Sorry, you can will be colored dark red which is &4 and the rest will default to the assign category color which is Textcolor. 

So issue with this is that the user generally won't know where the scoreboard will make a line break. Perhaps it's best to just use color codes everywhere then.

**Comment by Vanmc** [comment]
I just checked the code it seems that you can make a line break if you do a double space as long as the line is composed of 14 or 16 w/color codes characters

**Comment by RoboMWM** [comment]
> I still haven't seen any statistics did I do something wrong or it wont show until a specified time

I have absolutely no clue how metrics works, and as interesting as I find it, it might be a while before I decide to really spend time figuring it out. (Probably is easy to do if I look up documentation on it...)

As for the colors... so even before the hotfix you PR'd, are you able to change the color of the entire line using color codes? Or was that never the case prior?

**Comment by Vanmc** [comment]
> As for the colors... so even before the hotfix you PR'd, are you able to change the color of the entire line using color codes?

No

**Comment by RoboMWM** [comment]
> No

Ok, if that's what the case was before, then this is good to go. And now people are going to have duplicate threshold nodes, yay :P

**Comment by RoboMWM** [comment]
Hmm, well, if the messages used a color code for the entire message... Then how was it able to color the entire line before...?

**Comment by RoboMWM** [comment]
Hmm, actually it's not coloring lines for me at all in 3.8.2. Thought I remember it coloring lines before, I guess not? :S

**Comment by RoboMWM** [comment]
Hmm, so after applying this on my server and setting remove color codes to false, I get this: 

I'm also wondering if you now broke those who elect to use chat messages instead of the scoreboard :|

**Comment by RoboMWM** [comment]
Hmm, seems to be the same situation on 3.8.2 if I disable color removal: http://i.imgur.com/lYLAm3q.png

Fun.

**Comment by RoboMWM** [comment]
Wow, this scoreboard stuff is a huge mess.

**Comment by Vanmc** [comment]
I'll be honest with you I did not touch anything with the scoreboard system. I seemly went removed the issue with the scoreboard title and explained to you the issue about why you can use the color codes despite not using ChatColor and why ChatColor causes the redundancy.  I have the commits which shows that.

**Comment by Vanmc** [comment]
I have tested it on 1.8.8 and the problem did exist before  http://i.imgur.com/nUKR7nw.png

**Comment by RoboMWM** [comment]
Yeah I know I'm just trying to look into how a message is processed and it's just a mess of tons of undocumented methods

**Comment by RoboMWM** [comment]
By the way, what was the config you used to test that on 1.8.8 @Vanmc ?

**Comment by Vanmc** [comment]
Its a modified messages.yml to show the issue exist

`    Enable: true`
`    Scoreboard Title: "\xa7cExtraHardMode"`
`    Remove All Color Codes: false`

`    Msg: '&4You''re carrying too much weight to swim!'`

The default is Remove All Color Codes: true and Msg: You''re carrying too much weight to swim!

**Comment by RoboMWM** [comment]
btw, wrap stuff you're pasting in three backticks: See https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

It makes things look a lot nicer and easier to follow.

**Pull request merged**
