### PR TITLE
You left these out when you were fixing stuff,

### PR DESCRIPTION
**Pull request by erik1988**
thus they need to be re added for these to work.

### CODE REVIEW

**Comment by RoboMWM** [comment]
Can you point me to the commit in question?

**Comment by erik1988** [comment]
https://github.com/MLG-Fortress/ExtraHardMode/pull/75

**Comment by erik1988** [comment]
https://github.com/erik1988/ExtraHardMode/commit/3edd9bfa6f0cdea078f475b3c80460eeda41c63e

**Comment by RoboMWM** [comment]
Huh, I guess I forgot to put them back in then.

**Pull request merged**
