### PR TITLE
Some fixes and improvements. 

### PR DESCRIPTION
**Pull request by erik1988**
See the commits for details.

### CODE REVIEW

**Comment by RoboMWM** [comment]
Hmm, I still feel this is a subjective change... Not sure if you can/willing to either add config options for this, or instead a simple "mode" toggle to switch between the old and new mode you propose (and such a config option should be an int/string in case anyone else wants to add different "modes").

**Comment by RoboMWM** [comment]
Alright, just let me know when you get the chance to test.

I guess I'll leave the default config value to true, and I could set it back to false if people complain.

**Comment by erik1988** [comment]
it works well you can accept it.

**Comment by RoboMWM** [comment]
Uhhhh can you explain the console error with that last commit you added there....

**Comment by erik1988** [comment]
Well if you clicked the commit you would see that it's related. They probably changed the way you make zombies into villagers, so it does not work the way it used to. So as an easy fix i just changed them to normal zombies.

**Comment by RoboMWM** [comment]
FYI was the exception you received similar to this? https://github.com/MLG-Fortress/ExtraHardMode/issues/62

**Comment by erik1988** [comment]
Yes. You probably want to check those out, You still have two more of them in the plugin.
https://github.com/MLG-Fortress/ExtraHardMode/search?utf8=%E2%9C%93&q=setVillager

**Pull request merged**
